import EditorSection from "./components/Editor/EditorSection/EditorSection";
import TitleSection from "@/components/Title/TitleSection/TitleSection";

function App() {
  const data = {
    time: 1752215486521,
    blocks: [
      {
        id: "_h0FJetfDX",
        type: "unifiedImage",
        data: {
          images: [
            {
              url: "https://kr1-api-object-storage.nhncloudservice.com/v1/AUTH_96c6313b6d6a405b9511658326418a69/lotte-foundation/uploads/2025-07-04/23d493c2-7796-4e49-9132-7d2d9d1b161f.jpg",
              name: "[붙임7] 인도네시아 장학금 전달식.jpg",
              size: 4881420,
              type: "image/jpeg",
              width: 768,
              height: 511.9319329965434,
              ratio: 1.500199441563622,
            },
          ],
          caption: "",
          align: "center",
        },
      },
      {
        id: "LsL4fLYmBy",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"><b>&lt;사진&gt;&nbsp;롯데장학재단 장혜선 이사장이 인도네시아 현지 장학생들과 함께 기념사진을 촬영하고 있다.</b></span>',
          realText:
            "&lt;사진&gt;&nbsp;롯데장학재단 장혜선 이사장이 인도네시아 현지 장학생들과 함께 기념사진을 촬영하고 있다.",
          align: "center",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "tgg057QQPC",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "NEoztbH-OX",
        type: "paragraph",
        data: {
          text: '<span style="font-size: 20px; display: inline-block; word-break: break-word;"><b>인도네시아 10개 대학에서 장학생 선발…상반기에만 장학금 총 3,330만원 지급</b></span>',
          realText:
            "인도네시아 10개 대학에서 장학생 선발…상반기에만 장학금 총 3,330만원 지급",
          align: "center",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "7ZI_AhjNG2",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"><b><span style="font-size: 20px; display: inline-block; word-break: break-word;">자카르타 지역 7개 초등학교에 노후화된 화이트보드, 책상∙의자 세트 등 학습물품 지원</span></b></span>',
          realText:
            "자카르타 지역 7개 초등학교에 노후화된 화이트보드, 책상∙의자 세트 등 학습물품 지원",
          align: "center",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "YjJ3Jym9CX",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "sFhB8akavw",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "Dw51rvjhfE",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">롯데장학재단(이사장 장혜선)이 지난 2일(수) 인도네시아 자카르타에 위치한 롯데몰 자카르타 ‘Ice Palace’에서 ‘신격호 롯데 글로벌 장학금 수여식’을 진행하고, 올해 상반기 인도네시아 현지 성적우수 및 저소득층 대학생 50명에게 총 3,330만원 상당의 장학금을 전달했다.</span>',
          realText:
            "롯데장학재단(이사장 장혜선)이 지난 2일(수) 인도네시아 자카르타에 위치한 롯데몰 자카르타 ‘Ice Palace’에서 ‘신격호 롯데 글로벌 장학금 수여식’을 진행하고, 올해 상반기 인도네시아 현지 성적우수 및 저소득층 대학생 50명에게 총 3,330만원 상당의 장학금을 전달했다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "KGgwIhT0sb",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "OsCFMAUPvs",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">이번 상반기 ‘신격호 롯데 글로벌 장학금’은 인도네시아 내 10개 대학에서 선발된 학생들에게 1인당 450달러씩 지급되며, 전체 지원 규모는 총 22,500달러, 한화 약 3,330만원에 달한다.</span><span style="display: inline-block; word-break: break-word;">올해 재단에서 선정한 수혜 대학 10개교에는 University of Indonesia, Bandung Institute of Technology, Prasetya Mulya University 등 인도네시아 주요 대학들이 포함됐으며, 장학생은 성적 우수자와 저소득층을 각 50% 비율로 선발해 교육 기회의 공정성과 형평성을 동시에 고려했다.</span>',
          realText:
            "이번 상반기 ‘신격호 롯데 글로벌 장학금’은 인도네시아 내 10개 대학에서 선발된 학생들에게 1인당 450달러씩 지급되며, 전체 지원 규모는 총 22,500달러, 한화 약 3,330만원에 달한다.올해 재단에서 선정한 수혜 대학 10개교에는 University of Indonesia, Bandung Institute of Technology, Prasetya Mulya University 등 인도네시아 주요 대학들이 포함됐으며, 장학생은 성적 우수자와 저소득층을 각 50% 비율로 선발해 교육 기회의 공정성과 형평성을 동시에 고려했다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "NPsxSo7qOR",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "yWWATLE5j9",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">이날 전달식에는 장혜선 롯데장학재단 이사장을 비롯해 인도네시아 롯데 현지 법인장 10명 및 장학생 40명이 참석했다.</span><span style="display: inline-block; word-break: break-word;">장혜선 롯데장학재단 이사장은 이날 전달식에서 “저희 재단이 인도네시아에 처음 장학금을 전달한 것이 2009년이었는데, 오랜 기간 인연을 맺어 온 만큼 이제 인도네시아가 굉장히 가깝게 느껴진다”며 “‘신격호 롯데 글로벌 장학금’은 경제적으로 어려운 환경에서도 글로벌 리더로 성장할 수 있는 우수 인재를 발굴해 지원하는 사업”이라고 밝혔다.</span>',
          realText:
            "이날 전달식에는 장혜선 롯데장학재단 이사장을 비롯해 인도네시아 롯데 현지 법인장 10명 및 장학생 40명이 참석했다.장혜선 롯데장학재단 이사장은 이날 전달식에서 “저희 재단이 인도네시아에 처음 장학금을 전달한 것이 2009년이었는데, 오랜 기간 인연을 맺어 온 만큼 이제 인도네시아가 굉장히 가깝게 느껴진다”며 “‘신격호 롯데 글로벌 장학금’은 경제적으로 어려운 환경에서도 글로벌 리더로 성장할 수 있는 우수 인재를 발굴해 지원하는 사업”이라고 밝혔다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "dvxiPe6n2f",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "fIecqdXIHa",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">이어 “대한민국도 정말 어려운 시기를 겪었지만, 다른 나라의 도움 덕분에 지금은 선진국이 될 수 있었기에 이제는 그 도움을 다시 돌려드려야 할 때”라며 “국경을 넘어 이제는 우리가 하나라는 마음으로 같이 성장해나가야 한다고 생각한다”고 강조했다.</span>',
          realText:
            "이어 “대한민국도 정말 어려운 시기를 겪었지만, 다른 나라의 도움 덕분에 지금은 선진국이 될 수 있었기에 이제는 그 도움을 다시 돌려드려야 할 때”라며 “국경을 넘어 이제는 우리가 하나라는 마음으로 같이 성장해나가야 한다고 생각한다”고 강조했다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "MKrDGO1VJk",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "vuv3jc-Fig",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">또한 장 이사장은 “이번 장학금이 국경을 넘어 함께 성장하는 글로벌 나눔의 선순환을 만들어가는 하나의 상징이 되길 바란다”며 “이런 뜻깊은 자리에 함께해 주신 롯데 계열사 인도네시아 법인장들께도 진심으로 감사드린다. 물심양면으로 저희를 도와주셔서 꼭 필요한 학생들에게 도움의 손길을 전할 수 있었다”고 감사의 뜻을 전했다.</span>',
          realText:
            "또한 장 이사장은 “이번 장학금이 국경을 넘어 함께 성장하는 글로벌 나눔의 선순환을 만들어가는 하나의 상징이 되길 바란다”며 “이런 뜻깊은 자리에 함께해 주신 롯데 계열사 인도네시아 법인장들께도 진심으로 감사드린다. 물심양면으로 저희를 도와주셔서 꼭 필요한 학생들에게 도움의 손길을 전할 수 있었다”고 감사의 뜻을 전했다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "61RyH36VRa",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "yfRU-Y3DMh",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">이어 “이 자리에 함께 해주신 여러분의 응원에 진심으로 감사드린다”며, “저는 사람이라면 적어도 내게 도움을 주는 사람은 기억해야 한다고 생각한다. 대한민국의 롯데그룹과 롯데재단을 잊지 말아주시기 바란다”고 덧붙였다.</span>',
          realText:
            "이어 “이 자리에 함께 해주신 여러분의 응원에 진심으로 감사드린다”며, “저는 사람이라면 적어도 내게 도움을 주는 사람은 기억해야 한다고 생각한다. 대한민국의 롯데그룹과 롯데재단을 잊지 말아주시기 바란다”고 덧붙였다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "F-jO2ACvo6",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "o0JRpQmf8d",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">끝으로 “앞으로도 롯데장학재단은 인도네시아를 비롯한 도움이 필요한 국가의 학생들을 지속적으로 지원해 나갈 계획이며, 이번에 장학금을 받은 50명의 학생 모두가 인도네시아를 넘어 글로벌 리더로 성장하길 기대한다”고 밝혔다.</span>',
          realText:
            "끝으로 “앞으로도 롯데장학재단은 인도네시아를 비롯한 도움이 필요한 국가의 학생들을 지속적으로 지원해 나갈 계획이며, 이번에 장학금을 받은 50명의 학생 모두가 인도네시아를 넘어 글로벌 리더로 성장하길 기대한다”고 밝혔다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "1RPsY70Qsh",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "HnYpYUxwU5",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">롯데장학재단은 다음 날인 3일(목) 인도네시아 자카르타 지역에 위치한 SD Triwibawa 초등학교에서 ‘신격호 롯데 인도네시아 초등학교 물품 전달식’을 열고, 자카르타 내 7개 초등학교에 총 2,350만원 상당의 학습 물품을 지원했다.</span>',
          realText:
            "롯데장학재단은 다음 날인 3일(목) 인도네시아 자카르타 지역에 위치한 SD Triwibawa 초등학교에서 ‘신격호 롯데 인도네시아 초등학교 물품 전달식’을 열고, 자카르타 내 7개 초등학교에 총 2,350만원 상당의 학습 물품을 지원했다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "G6ee5-BY-Y",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "38FXjnqg45",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">이번 지원을 통해 화이트보드와 책상∙의자 세트 등 교내 노후화된 학습 기자재가 교체되며, 자카르타 지역 7개교 54개 학급, 총 691명의 초등학생들이 혜택을 받는다.</span>',
          realText:
            "이번 지원을 통해 화이트보드와 책상∙의자 세트 등 교내 노후화된 학습 기자재가 교체되며, 자카르타 지역 7개교 54개 학급, 총 691명의 초등학생들이 혜택을 받는다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "YcnXJzCvmQ",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "iQWBfkjFQ9",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">물품 전달식에는 장혜선 이사장과 인도네시아 롯데 현지 법인장 8명이 참석해 자리를 빛냈다.</span>',
          realText:
            "물품 전달식에는 장혜선 이사장과 인도네시아 롯데 현지 법인장 8명이 참석해 자리를 빛냈다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "7ncjMqiRZl",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "1NHwIg3DQl",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">장혜선 이사장은 “인도네시아 학생들이 공부하고 싶어도 열악한 학습 환경 때문에 마음 놓고 공부에 집중하기 어려운 현실이 개인적으로 늘 안타까웠다”며 “저희 재단에서 지금까지 다양한 방식으로 인도네시아 학생들을 도왔는데, 이번에는 화이트보드, 책상, 의자 세트를 지원해 학생들이 공부하는 환경을 개선하여 학업에 전념할 수 있도록 돕고자 했다”고 밝혔다.</span>',
          realText:
            "장혜선 이사장은 “인도네시아 학생들이 공부하고 싶어도 열악한 학습 환경 때문에 마음 놓고 공부에 집중하기 어려운 현실이 개인적으로 늘 안타까웠다”며 “저희 재단에서 지금까지 다양한 방식으로 인도네시아 학생들을 도왔는데, 이번에는 화이트보드, 책상, 의자 세트를 지원해 학생들이 공부하는 환경을 개선하여 학업에 전념할 수 있도록 돕고자 했다”고 밝혔다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "1SqxFPzNiM",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "THCTyVvRu3",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">이어 “교육의 평등은 누구나 편하게 공부할 수 있는 환경을 만들어주는 것에서부터 시작된다고 생각한다”며 “이번 물품 지원 사업이 인도네시아 교육의 평등을 만들어 내는 한 장의 벽돌이 될 수 있을 것이라 믿는다”고 강조했다.</span>',
          realText:
            "이어 “교육의 평등은 누구나 편하게 공부할 수 있는 환경을 만들어주는 것에서부터 시작된다고 생각한다”며 “이번 물품 지원 사업이 인도네시아 교육의 평등을 만들어 내는 한 장의 벽돌이 될 수 있을 것이라 믿는다”고 강조했다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "7liIe2Jyc8",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "zaijd8cDv9",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span><span style="display: inline-block; word-break: break-word;">또한 “이번 지원이 원활히 진행될 수 있도록 협조해주신 롯데 계열사 현지 법인 관계자 여러분께도 깊이 감사드린다”며 “앞으로도 롯데장학재단은 인도네시아 학생들이 평등한 교육 기회를 누릴 수 있도록 다양한 방면에서 지속적으로 고민하고 노력해 나가겠다”고 말했다.</span>',
          realText:
            "또한 “이번 지원이 원활히 진행될 수 있도록 협조해주신 롯데 계열사 현지 법인 관계자 여러분께도 깊이 감사드린다”며 “앞으로도 롯데장학재단은 인도네시아 학생들이 평등한 교육 기회를 누릴 수 있도록 다양한 방면에서 지속적으로 고민하고 노력해 나가겠다”고 말했다.",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "DfpFCkFNVU",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "Iua0f-Cnra",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">롯데장학재단은 가파르게 성장하는 아세안 및 남아시아 지역의 우수한 인재들을 자국 성장과 발전에 기여하는 글로벌 리더로 키우고자 2008년부터 글로벌 장학금 지원사업을 진행하고 있으며, 현재 베트남, 인도네시아, 캄보디아, 필리핀 등 총 4개국 인재들의 학업을 후원해오고 있다.</span>',
          realText:
            "롯데장학재단은 가파르게 성장하는 아세안 및 남아시아 지역의 우수한 인재들을 자국 성장과 발전에 기여하는 글로벌 리더로 키우고자 2008년부터 글로벌 장학금 지원사업을 진행하고 있으며, 현재 베트남, 인도네시아, 캄보디아, 필리핀 등 총 4개국 인재들의 학업을 후원해오고 있다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "xjJGiqsMEN",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;"></span>',
          realText: "",
          align: "left",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
      {
        id: "_pAG34ChSi",
        type: "paragraph",
        data: {
          text: '<span style="display: inline-block; word-break: break-word;">특히 이번에 방문한 인도네시아의 경우, 지난해 자카르타 3개 초등학교 도서관 건립에 1억원을 지원하고, 10개 대학 장학생 50명에게 6,600만원의 장학금을 전달한 바 있다.</span>',
          realText:
            "특히 이번에 방문한 인도네시아의 경우, 지난해 자카르타 3개 초등학교 도서관 건립에 1억원을 지원하고, 10개 대학 장학생 50명에게 6,600만원의 장학금을 전달한 바 있다.",
          align: "justify",
          letterSpacing: "normal",
          lineHeight: "normal",
          isBold: false,
          isItalic: false,
          isUnderline: false,
          isStrikethrough: false,
          fontSize: "",
          fontFamily: "",
        },
      },
    ],
    version: "2.30.7",
  };

  return (
    <div className="App">
      {/* <TitleSection /> */}
      <EditorSection value={data} width="912px" />
    </div>
  );
}

export default App;
